#!/usr/bin/env python3
"""Downloads and prepares the UI art: flags, icons, fonts and panel textures.

Everything is freely licensed:
  Flags  - flag-icons by Panayiotis Lipiridis (MIT)            https://github.com/lipis/flag-icons
  Icons  - game-icons.net by Lorc and Delapouite (CC BY 3.0)    https://game-icons.net
  Fonts  - Barlow by Jeremy Tribby (SIL Open Font License)      https://github.com/google/fonts
Panel gradients and the screen vignette are generated by the game itself (Ui.cs).

Flags and icons go to Assets/StreamingAssets/UI/{Flags,Icons}: the game decodes them at
runtime, so they never depend on Unity's texture import settings. Fonts go to
Assets/Resources/Fonts. Credits are listed in Assets/Resources/Credits.txt and the README.

Usage:
  pip install cairosvg pillow
  python3 Tools/assets/fetch_ui_assets.py
"""

import io
import json
import os
import re
import sys
import urllib.request

from PIL import Image, ImageDraw

try:
    import cairosvg
except ImportError:
    sys.exit("pip install cairosvg")

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
RES = os.path.join(ROOT, "Assets", "Resources")
UI_IMAGES = os.path.join(ROOT, "Assets", "StreamingAssets", "UI")
CACHE = os.path.join(os.path.dirname(__file__), ".cache")

FLAG_URL = "https://raw.githubusercontent.com/lipis/flag-icons/main/flags/4x3/{}.svg"
ICON_URL = "https://raw.githubusercontent.com/game-icons/icons/master/{}.svg"
FONT_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/{}"

# Our icon name -> game-icons path.
ICONS = {
    "treasury": "delapouite/money-stack",
    "debt": "delapouite/bank",
    "gdp": "delapouite/histogram",
    "growth": "lorc/profit",
    "stability": "lorc/checked-shield",
    "approval": "delapouite/thumb-up",
    "population": "delapouite/three-friends",
    "government": "delapouite/podium",
    "ballot": "delapouite/vote",
    "diplomacy": "delapouite/shaking-hands",
    "handshake": "delapouite/shaking-hands",
    "dove": "lorc/dove",
    "trade": "lorc/trade",
    "ship": "delapouite/cargo-ship",
    "sanctions": "lorc/padlock",
    "alliance": "delapouite/flag-objective",
    "alliance_leave": "lorc/broken-shield",
    "war": "lorc/crossed-swords",
    "denounce": "delapouite/megaphone",
    "protest": "delapouite/barricade",
    "news": "delapouite/newspaper",
    "scandal": "delapouite/newspaper",
    "disaster": "delapouite/flood",
    "chip": "lorc/processor",
    "energy": "delapouite/oil-pump",
    "strike": "lorc/gears",
    "factory": "delapouite/factory",
    "military": "lorc/tank",
    "education": "delapouite/graduate-cap",
    "infrastructure": "delapouite/crane",
    "welfare": "delapouite/hand-bandage",
    "admin": "delapouite/stamper",
    "calendar": "delapouite/calendar",
    "settings": "lorc/cog",
    "political": "delapouite/earth-africa-europe",
    "wealth": "delapouite/pay-money",
    "income": "delapouite/receive-money",
    "capital": "delapouite/position-marker",
    "media": "delapouite/tv",
    "reform": "lorc/scroll-unfurled",
    "crown": "lorc/crown",
    "trophy": "delapouite/diamond-trophy",
    "bank": "delapouite/bank",
    "speaker": "delapouite/speaker",
    "mute": "delapouite/speaker-off",
    "person": "delapouite/person",
}

FONTS = {
    "BarlowSemiCondensed-Regular.ttf": "barlowsemicondensed/BarlowSemiCondensed-Regular.ttf",
    "BarlowSemiCondensed-Medium.ttf": "barlowsemicondensed/BarlowSemiCondensed-Medium.ttf",
    "BarlowSemiCondensed-SemiBold.ttf": "barlowsemicondensed/BarlowSemiCondensed-SemiBold.ttf",
    "BarlowSemiCondensed-Bold.ttf": "barlowsemicondensed/BarlowSemiCondensed-Bold.ttf",
    "BarlowCondensed-Bold.ttf": "barlowcondensed/BarlowCondensed-Bold.ttf",
    "OFL.txt": "barlowsemicondensed/OFL.txt",
}

# Countries Natural Earth has no ISO code for, or flag-icons has no flag for.
ISO_OVERRIDES = {"KOS": "xk", "SAH": "eh", "PSX": "ps"}


def fetch(url, cache_name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, cache_name)
    if not os.path.exists(path):
        with urllib.request.urlopen(url, timeout=60) as r:
            data = r.read()
        with open(path, "wb") as f:
            f.write(data)
    with open(path, "rb") as f:
        return f.read()


def svg_to_image(svg_bytes, width, height):
    png = cairosvg.svg2png(bytestring=svg_bytes, output_width=width, output_height=height)
    return Image.open(io.BytesIO(png)).convert("RGBA")


def fallback_flag(color_hex, width, height):
    """A simple horizontal tricolour in the country's map colour, for places with no flag."""
    rgb = tuple(int(color_hex[i:i + 2], 16) for i in (1, 3, 5))
    dark = tuple(int(c * 0.55) for c in rgb)
    img = Image.new("RGBA", (width, height), rgb + (255,))
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, width, height // 3], fill=dark + (255,))
    d.rectangle([0, 2 * height // 3, width, height], fill=dark + (255,))
    return img


def build_flags():
    out = os.path.join(UI_IMAGES, "Flags")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(ROOT, "Assets", "StreamingAssets", "Data", "Map", "countries.json"), encoding="utf-8") as f:
        countries = json.load(f)["countries"]
    made = fallback = 0
    for c in countries:
        iso = ISO_OVERRIDES.get(c["tag"], (c.get("isoA2") or "").lower())
        img = None
        if len(iso) == 2 and iso.isalpha():
            try:
                img = svg_to_image(fetch(FLAG_URL.format(iso), f"flag_{iso}.svg"), 128, 96)
            except Exception as e:  # missing flag or network error
                print(f"  no flag for {c['tag']} ({iso}): {e}")
        if img is None:
            img = fallback_flag(c["color"], 128, 96)
            fallback += 1
        else:
            made += 1
        img.save(os.path.join(out, f"{c['tag']}.png"), optimize=True)
    print(f"Flags: {made} real, {fallback} generated")


def build_icons():
    out = os.path.join(UI_IMAGES, "Icons")
    os.makedirs(out, exist_ok=True)
    for name, path in ICONS.items():
        svg = fetch(ICON_URL.format(path), path.replace("/", "_") + ".svg").decode("utf-8")
        # game-icons SVGs are a white glyph on a black square: drop the square, keep the glyph white.
        svg = re.sub(r'<path d="M0 0h512v512H0z"\s*/>', "", svg)
        img = svg_to_image(svg.encode("utf-8"), 64, 64)
        img.save(os.path.join(out, f"{name}.png"), optimize=True)
    print(f"Icons: {len(ICONS)}")


def build_fonts():
    out = os.path.join(RES, "Fonts")
    os.makedirs(out, exist_ok=True)
    for name, path in FONTS.items():
        data = fetch(FONT_URL.format(path), name)
        with open(os.path.join(out, name), "wb") as f:
            f.write(data)
    print(f"Fonts: {len(FONTS)} files")


def write_credits():
    text = """Third-party art used in this game
================================

Flags: flag-icons by Panayiotis Lipiridis and contributors - MIT License
  https://github.com/lipis/flag-icons

Icons: game-icons.net by Lorc (https://lorcblog.blogspot.com) and Delapouite (https://delapouite.com)
  Licensed under Creative Commons Attribution 3.0 (CC BY 3.0) - https://creativecommons.org/licenses/by/3.0/
  Recoloured to white for the interface.

Fonts: Barlow by Jeremy Tribby - SIL Open Font License 1.1 (see Fonts/OFL.txt)
  https://github.com/google/fonts/tree/main/ofl/barlowsemicondensed

Map data and terrain: Natural Earth - public domain
  https://www.naturalearthdata.com/
"""
    with open(os.path.join(RES, "Credits.txt"), "w", encoding="utf-8") as f:
        f.write(text)


def main():
    build_flags()
    build_icons()
    build_fonts()
    write_credits()


if __name__ == "__main__":
    main()
